// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/compare": {
            "post": {
                "description": "Returns spelling, missing, extra, punctuation errors etc.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Compare original and user text",
                "parameters": [
                    {
                        "description": "Texts to compare",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.CompareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.CompareAnalytics"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.CompareAnalytics": {
            "type": "object",
            "properties": {
                "count_mistakes": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.WordResult"
                    }
                },
                "similarity": {
                    "type": "number"
                },
                "total_score": {
                    "type": "number"
                }
            }
        },
        "main.CompareRequest": {
            "description": "API for comparing original and user dictation text.",
            "type": "object",
            "required": [
                "original",
                "user"
            ],
            "properties": {
                "original": {
                    "type": "string"
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "main.WordResult": {
            "type": "object",
            "properties": {
                "has_mistake": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "mistake_type": {
                    "type": "string"
                },
                "original_word": {
                    "type": "string"
                },
                "removed_points": {
                    "type": "number"
                },
                "word": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Dictation Analytic API",
	Description:      "API for comparing original and user dictation text.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
